// The ~90 location keyword phrases from the reference sheets. Each is a
// template with a {city} placeholder that the location pages render with the
// specific city/area name. Used for on-page keyword chips, the SEO keywords
// array, and naturally woven into the generated copy.

export const KEYWORD_TEMPLATES: string[] = [
  'PhD Research Help in {city}',
  'Thesis Writing Service in {city}',
  'High Quality Thesis Writing in {city}',
  'Low Cost Thesis Writing in {city}',
  'Research Paper Writing in {city}',
  'Research Paper Writing Service in {city}',
  'Best Research Paper Writing in {city}',
  'Best Research Paper Writers in {city}',
  'Affordable Research Paper Writing in {city}',
  'Academic Writing Service in {city}',
  'Academic Writing Services in {city}',
  'Academic Editing Services in {city}',
  'Academic Research Support in {city}',
  'Literature Review Writing Services in {city}',
  'Journal Paper Writing in {city}',
  'Journal Publication Support in {city}',
  'IEEE Paper Writing in {city}',
  'Research Proposal Writing in {city}',
  'Budget Friendly Scopus Publication in {city}',
  'Budget Friendly SCI Publication in {city}',
  'Budget Friendly UGC Publication in {city}',
  'Affordable Journal Publication in {city}',
  'Affordable PhD Thesis Writing in {city}',
  'AI Research Implementation in {city}',
  'ATLAS.ti Data Analysis in {city}',
  'Best Academic Research Support in {city}',
  'Best Research Paper Writing Services in {city}',
  'Budget Friendly Research Paper Writing in {city}',
  'Budget Friendly Research Services in {city}',
  'Cheap Research Paper Service in {city}',
  'Cheap Research Paper Writing Service in {city}',
  'Research Writing Service in {city}',
  'Confidential Research Assistance in {city}',
  'Discounted Research Writing in {city}',
  'Economical Research Paper Writing in {city}',
  'End To End PhD Research Services in {city}',
  'End To End PhD Support in {city}',
  'Engineering Project Guidance in {city}',
  'Expert PhD Guidance in {city}',
  'Expert Research Implementation in {city}',
  'Expert Research Paper Assistance in {city}',
  'Express Research Paper Writing in {city}',
  'Fast Research Paper Writing in {city}',
  'Fast Scopus Publication Support in {city}',
  'Grant Writing Services in {city}',
  'High Quality Research Paper Writing in {city}',
  'Hire Research Writer in {city}',
  'Journal Publication Assistance in {city}',
  'Last Minute Research Paper Writing in {city}',
  'Low Budget Scopus Publication in {city}',
  'Low Cost Research Paper Writing in {city}',
  'Low Price Research Paper Writing in {city}',
  'Low Price SCI Publication in {city}',
  'Low Price Scopus Publication in {city}',
  'Low Price UGC Publication in {city}',
  'M.E Thesis Writing in {city}',
  'Machine Learning Research Support in {city}',
  'MATLAB Project Help in {city}',
  'Medical Research Writing in {city}',
  'Most Trusted PhD Research Assistance in {city}',
  'NVivo Data Analysis in {city}',
  'On Time Research Paper Writing in {city}',
  'Order Research Paper in {city}',
  'Original Research Paper Writing in {city}',
  'PhD Defense Preparation in {city}',
  'PhD Dissertation Writing Services in {city}',
  'PhD Research Assistance in {city}',
  'PhD Thesis Proofreading in {city}',
  'PhD Thesis Writing Help in {city}',
  'PhD Thesis Writing Services in {city}',
  'Plagiarism Free Research Paper in {city}',
  'Plagiarism Removal Services in {city}',
  'Premium Research Paper Writing in {city}',
  'Premium Thesis Writing Services in {city}',
  'Professional Journal Publication Support in {city}',
  'Professional Research Paper Writers in {city}',
  'Q1 Journal Publication Support in {city}',
  'Quality Research Paper Writing in {city}',
  'Quick Research Paper Help in {city}',
  'R Programming Data Analysis in {city}',
  'Reliable Research Consultancy in {city}',
  'Reliable Research Paper Writing in {city}',
  'Research Assistance in {city}',
  'Research Coding Services in {city}',
  'Research Consultancy in {city}',
  'Research Implementation Services in {city}',
  'Research Paper Editing in {city}',
  'Research Paper Publication Support in {city}',
  'Research Paper Support in {city}',
  'Research Paper Writing Services in {city}',
  'Research Writing Within Deadline in {city}',
  'SCI Publication Support in {city}',
  'Scopus Journal Publication Assistance in {city}',
  'Scopus Publication Services in {city}',
  'SPSS Data Analysis Services in {city}',
  'Student Friendly PhD Support in {city}',
  'Survey Data Collection Services in {city}',
  'Systematic Literature Review PRISMA in {city}',
  'Thesis Editing Services in {city}',
  'Top Research Paper Writers in {city}',
  'Trusted Academic Writing Service in {city}',
  'Trusted Scopus Publication Services in {city}',
  'Trusted Thesis Writing Company in {city}',
  'Urgent Research Paper Help in {city}',
  'Value For Money Research Paper Writing in {city}',
  'NVivo & ATLAS.ti Qualitative Analysis in {city}',
];

export function renderKeywords(city: string): string[] {
  return KEYWORD_TEMPLATES.map((t) => t.replace(/\{city\}/g, city));
}
